[build]
  base    = "frontend"
  command = "npm install --no-save --force @rollup/rollup-linux-x64-gnu@4.63.0 && npm run build"
  publish = "dist"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
